### PR TITLE
General changes to make the cookbook to work on chef12

### PR DESCRIPTION
**Pull request by alejandrod**
Chef12 loads the resources in a different way. So, these are minor changes to make sure it works fine on chef12

### CODE REVIEW

**Comment by babelop** [comment]
Thanks again @alejandrod. We'll review and publish your PR as soon as possible.

**Comment by alejandrod** [comment]
Hey, I'll be great if you can merge this. Otherwise is not possible to use the cookbook

**Comment by babelop** [comment]
I'm sorry this issue has lagged so far behind. Changes to our infrastructure have left our own Chef usage a bit in the stone-age. I'm happy to merge this pull request, but I'd feel more confortable doing so with the knowledge that it's still desired and verified from multiple sources. So anyone still interested (and especially who have tested this patch). Please comment.

**Comment by alejandrod** [comment]
As I said. I've been using this for a while, no problem. The only problems I had when upgrading Chef. So, that's the reason of the changes.

**Comment by alejandrod** [comment]
Could you please merge? thanks!

**Pull request merged**
